# Generated by Django 2.0.1 on 2018-09-29 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='img',
            field=models.ImageField(blank=True, upload_to='restaurant_images'),
        ),
    ]
