# Generated by Django 2.0.1 on 2018-09-29 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_restaurant_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
