# Generated by Django 2.0.1 on 2018-09-29 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_orderlist_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
